#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TIMESTAMP_UTC="$(date -u +"%Y%m%dT%H%M%SZ")"
RUN_ID="ble-proof-${TIMESTAMP_UTC}"
ARTIFACT_ROOT="${ROOT_DIR}/tests/e2e-harness/artifacts/ble-proof"
START_BTMON=0
BTMON_INTERFACE="hci0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --run-id)
      RUN_ID="$2"
      shift 2
      ;;
    --artifact-root)
      ARTIFACT_ROOT="$2"
      shift 2
      ;;
    --start-btmon)
      START_BTMON=1
      shift
      ;;
    --btmon-interface)
      BTMON_INTERFACE="$2"
      shift 2
      ;;
    *)
      echo "unknown arg: $1" >&2
      exit 1
      ;;
  esac
done

ARTIFACT_DIR="${ARTIFACT_ROOT}/${RUN_ID}"
mkdir -p "${ARTIFACT_DIR}"

ENV_SNAPSHOT_PATH="${ARTIFACT_DIR}/env-snapshot.txt"
DESKTOP_LOG_PATH="${ARTIFACT_DIR}/desktop-advertiser.log"
BTMON_LOG_PATH="${ARTIFACT_DIR}/btmon.log"
BTMON_PID_PATH="${ARTIFACT_DIR}/btmon.pid"
CHECKLIST_PATH="${ARTIFACT_DIR}/expected-evidence-checklist.md"
README_PATH="${ARTIFACT_DIR}/README.md"
IOS_NOTES_PATH="${ARTIFACT_DIR}/ios-observations.txt"

cat > "${ENV_SNAPSHOT_PATH}" <<EOF
run_id=${RUN_ID}
created_at_utc=${TIMESTAMP_UTC}
artifact_dir=${ARTIFACT_DIR}

[host]
hostname=$(hostname)
kernel=$(uname -srmo)

[git]
repo_root=${ROOT_DIR}
head_commit=$(git -C "${ROOT_DIR}" rev-parse HEAD 2>/dev/null || echo "unknown")
head_branch=$(git -C "${ROOT_DIR}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

[desktop_env_defaults]
AETHOS_BLE_ALLOW_LEGACY_NAME_HINTS=0
AETHOS_DISABLE_BLE=0
AETHOS_DISABLE_BLE_ADVERTISING=0

[desktop_env_current]
AETHOS_BLE_ALLOW_LEGACY_NAME_HINTS=${AETHOS_BLE_ALLOW_LEGACY_NAME_HINTS:-unset}
AETHOS_DISABLE_BLE=${AETHOS_DISABLE_BLE:-unset}
AETHOS_DISABLE_BLE_ADVERTISING=${AETHOS_DISABLE_BLE_ADVERTISING:-unset}

[desktop_log_path]
${DESKTOP_LOG_PATH}

[btmon_log_path]
${BTMON_LOG_PATH}
EOF

cat > "${CHECKLIST_PATH}" <<EOF
# Expected evidence checklist

- [ ] Desktop emits v2 wakeup hint on-air (UUID list only, no 0x21 service data).
- [ ] iOS scanner shows accepted_count > 0 for desktop signal.
- [ ] BLE-triggered encounter activation is observed.

## Desktop logs to capture

- [ ] ble_advertiser_started source=bluez-le-advertiser ...
- [ ] ble_wakeup_hint_accepted count=<n> source=ble_wakeup_v2
- [ ] encounter_ble_handoff ... reason=ble-discovery ...

## btmon logs to capture

- [ ] Aethos primary UUID in AD type 0x07 or 0x06
- [ ] No AD type 0x21 service data keyed by Aethos UUID (v2 forbids it)

## iOS logs to capture

- [ ] accepted Aethos peer log lines
- [ ] accepted_count / rejection_count deltas
- [ ] encounter activation event associated with BLE discovery
EOF

cat > "${IOS_NOTES_PATH}" <<EOF
Paste iOS scanner evidence here.

Suggested snippets:
- accepted_count lines
- rejection_count lines
- rejection reasons
- BLE-triggered encounter activation logs
EOF

cat > "${README_PATH}" <<EOF
# BLE proof artifact bundle

This directory is generated by scripts/collect-ble-proof-artifacts.sh.

Artifacts:

- env snapshot: ${ENV_SNAPSHOT_PATH}
- desktop advertiser log target: ${DESKTOP_LOG_PATH}
- btmon capture output target: ${BTMON_LOG_PATH}
- expected evidence checklist: ${CHECKLIST_PATH}
- iOS notes capture: ${IOS_NOTES_PATH}

## Manual commands

Run desktop advertiser (from repository root):

  cd "${ROOT_DIR}/spikes/tauri-desktop"
  AETHOS_BLE_ALLOW_LEGACY_NAME_HINTS=0 AETHOS_DISABLE_BLE=0 AETHOS_DISABLE_BLE_ADVERTISING=0 npm run tauri:dev 2>&1 | tee "${DESKTOP_LOG_PATH}"

Run btmon capture (separate terminal):

  sudo btmon -i "${BTMON_INTERFACE}" | tee "${BTMON_LOG_PATH}"

Canonical manual procedure remains:

- docs/testing/ble-canonical-advertiser-proof.md
EOF

if [[ "${START_BTMON}" == "1" ]]; then
  if ! command -v btmon >/dev/null 2>&1; then
    echo "btmon not found on PATH; cannot start capture" >&2
    exit 1
  fi
  if [[ -f "${BTMON_PID_PATH}" ]]; then
    echo "btmon pid file already exists at ${BTMON_PID_PATH}" >&2
    exit 1
  fi

  nohup sudo btmon -i "${BTMON_INTERFACE}" > "${BTMON_LOG_PATH}" 2>&1 &
  BTMON_PID=$!
  echo "${BTMON_PID}" > "${BTMON_PID_PATH}"
fi

echo "artifact_dir=${ARTIFACT_DIR}"
echo "env_snapshot=${ENV_SNAPSHOT_PATH}"
echo "desktop_log_path=${DESKTOP_LOG_PATH}"
echo "btmon_log_path=${BTMON_LOG_PATH}"
echo "checklist=${CHECKLIST_PATH}"
if [[ "${START_BTMON}" == "1" ]]; then
  echo "btmon_started_pid=$(cat "${BTMON_PID_PATH}")"
fi
